name: A workflow to test public action

on: [push]

jobs:
  eu_sunt_seful_tau_job:
    runs-on: ubuntu-latest
    name: Seful_job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Eu sunt seful tau
        id: seful
        uses: CostinManolescu/mesaj_seful@v1
        
      - name: Get the message
        run: echo "The message is ${{ steps.seful.outputs.message }}"

